In [10]:
#Q1
# given example
import numpy as np

v1 = np.array([1, 2])
v2 = np.array([3, 4])

matrix = np.column_stack((v1, v2))
det = np.linalg.det(matrix)

print("Determinant =", det)
if det != 0:
    print("Vectors are linearly independent")
else:
    print("Vectors are linearly dependent")


# user defined func.
def check_independence(v1, v2):
    matrix = np.column_stack((v1, v2))
    det = np.linalg.det(matrix)
    print("Determinant =", det)
    if det != 0:
        print("Vectors are linearly independent")
    else:
        print("Vectors are linearly dependent")

v1 = np.array([5, 0])
v2 = np.array([0, 5])

check_independence(v1, v2)


# user input
import numpy as np

def lin_dep(m):
    m = np.array(m)
    determinant = np.linalg.det(m)
    if np.isclose(determinant, 0):
        print("The set of vectors are linearly dependent.")
    else:
        print(f"Determinant = {determinant}")
        print("The set of vectors are linearly independent.")

n = int(input("Enter number of vectors: "))
r = int(input("Enter dimension of each vector: "))

m = []
for i in range(n):
    v = []
    print(f"Enter elements of vector {i+1}:")
    for j in range(r):
        v.append(float(input()))
    m.append(v)

lin_dep(m)

Determinant = -2.0
Vectors are linearly independent
Determinant = 24.999999999999996
Vectors are linearly independent
Enter number of vectors: 2
Enter dimension of each vector: 2
Enter elements of vector 1:
12
13
Enter elements of vector 2:
14
15
Determinant = -2.0000000000000173
The set of vectors are linearly independent.


In [11]:
# Q2
# given example
import numpy as np

v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([1, 0])

matrix = np.column_stack((v1, v2, v3))
rank = np.linalg.matrix_rank(matrix)

print("Rank =", rank)
if rank == 2:
    print("Vectors are linearly independent")
else:
    print("Vectors are linearly dependent")


# user defined func.
def check_rank(v1, v2, v3):
    matrix = np.column_stack((v1, v2, v3))
    rank = np.linalg.matrix_rank(matrix)
    print("Rank =", rank)
    if rank == 2:
        print("Vectors are linearly independent")
    else:
        print("Vectors are linearly dependent")

v1 = np.array([2, 1])
v2 = np.array([4, 2])
v3 = np.array([6, 3])

check_rank(v1, v2, v3)


# user input
import numpy as np

def check_rank(m):
    m = np.array(m)
    rank = np.linalg.matrix_rank(m)
    print("Rank =", rank)
    if rank == m.shape[0]:
        print("Vectors are linearly independent")
    else:
        print("Vectors are linearly dependent")

n = int(input("Enter number of vectors: "))
r = int(input("Enter dimension of each vector: "))

m = []
for i in range(n):
    v = []
    print(f"Enter elements of vector {i+1}:")
    for j in range(r):
        v.append(float(input()))
    m.append(v)

m = np.array(m).T
check_rank(m)

Rank = 2
Vectors are linearly independent
Rank = 1
Vectors are linearly dependent
Enter number of vectors: 3
Enter dimension of each vector: 2
Enter elements of vector 1:
1
2
Enter elements of vector 2:
9
8
Enter elements of vector 3:
5
4
Rank = 2
Vectors are linearly independent


In [13]:
#Q3
# given example
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([2,4,6])
v3 = np.array([3,6,9])

matrix = np.column_stack((v1, v2, v3))
rank = np.linalg.matrix_rank(matrix)

print("Rank =", rank)
if rank < 3:
    print("Vectors are linearly dependent")
else:
    print("Vectors are linearly independent")


# user defined func.
def check_dep(vectors):
    matrix = np.column_stack(vectors)
    rank = np.linalg.matrix_rank(matrix)
    print("Rank =", rank)
    if rank < len(vectors):
        print("Vectors are linearly dependent")
    else:
        print("Vectors are linearly independent")

v1 = np.array([1,0,1])
v2 = np.array([2,1,3])
v3 = np.array([3,1,4])

check_dep([v1, v2, v3])


# user input
import numpy as np

def check_dep(m):
    m = np.array(m)
    m = m.T
    rank = np.linalg.matrix_rank(m)
    print("Rank =", rank)
    if rank < m.shape[1]:
        print("Vectors are linearly dependent")
    else:
        print("Vectors are linearly independent")

n = int(input("Enter number of vectors: "))
r = int(input("Enter dimension of each vector: "))

m = []
for i in range(n):
    v = []
    print(f"Enter elements of vector {i+1}:")
    for j in range(r):
        v.append(float(input()))
    m.append(v)

check_dep(m)

Rank = 1
Vectors are linearly dependent
Rank = 2
Vectors are linearly dependent
Enter number of vectors: 3
Enter dimension of each vector: 3
Enter elements of vector 1:
10
20
30
Enter elements of vector 2:
20
40
60
Enter elements of vector 3:
30
60
90
Rank = 1
Vectors are linearly dependent


In [15]:
#Q4
# given example
import numpy as np

v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])

matrix = np.column_stack((v1, v2, v3))
rank = np.linalg.matrix_rank(matrix)

print("Rank =", rank)
if rank == len([v1, v2, v3]):
    print("Vectors are linearly independent")
else:
    print("Vectors are linearly dependent")


# user defined func.
def check_ind(vectors):
    matrix = np.column_stack(vectors)
    rank = np.linalg.matrix_rank(matrix)
    print("Rank =", rank)
    if rank == len(vectors):
        print("Vectors are linearly independent")
    else:
        print("Vectors are linearly dependent")

v1 = np.array([9,0,9])
v2 = np.array([6,2,0])
v3 = np.array([0,6,8])

check_ind([v1, v2, v3])


# user input
import numpy as np

def check_ind(m):
    m = np.array(m)
    m = m.T
    rank = np.linalg.matrix_rank(m)
    print("Rank =", rank)
    if rank == m.shape[1]:
        print("Vectors are linearly independent")
    else:
        print("Vectors are linearly dependent")

n = int(input("Enter number of vectors: "))
r = int(input("Enter dimension of each vector: "))

m = []
for i in range(n):
    v = []
    print(f"Enter elements of vector {i+1}:")
    for j in range(r):
        v.append(float(input()))
    m.append(v)

check_ind(m)

Rank = 3
Vectors are linearly independent
Rank = 3
Vectors are linearly independent
Enter number of vectors: 3
Enter dimension of each vector: 3
Enter elements of vector 1:
1
5
6
Enter elements of vector 2:
3
4
9
Enter elements of vector 3:
0
0
1
Rank = 3
Vectors are linearly independent


In [25]:
#Q5
# Rank = number of linearly independent vectors
# If rank == number of vectors → linearly independent
# If rank < number of vectors → linearly dependent

import numpy as np
from numpy.linalg import matrix_rank

def check(vectors):
    m = np.array(vectors)
    rank = matrix_rank(m)

    print("Vectors:")
    print(m)
    print("Rank:", rank)
    print("Number of vectors:", len(vectors))

    if rank == len(vectors):
        print("Result: Vectors are Linearly Independent\n")
    else:
        print("Result: Vectors are Linearly Dependent\n")


# Example 1: Linearly Independent
vectors1 = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

check(vectors1)

# Example 2: Linearly Dependent
vectors2 = [
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
]

check(vectors2)

Vectors:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Rank: 3
Number of vectors: 3
Result: Vectors are Linearly Independent

Vectors:
[[1 2 3]
 [2 4 6]
 [3 6 9]]
Rank: 1
Number of vectors: 3
Result: Vectors are Linearly Dependent



In [28]:
from google.colab import files
uploaded = files.upload()

Saving dataset_3.csv to dataset_3.csv
Saving dataset_2.csv to dataset_2.csv
Saving dataset_1.csv to dataset_1.csv


In [30]:
#TASK 1
import pandas as pd
import numpy as np
from numpy.linalg import matrix_rank

df = pd.read_csv("dataset_1.csv")

print("Dataset 1:")
print(df)

X = df.values
rank_X = matrix_rank(X)

print("\nNumber of features:", df.shape[1])
print("Rank of dataset:", rank_X)

redundant_features = []

for col in df.columns:
    temp_df = df.drop(columns=[col])
    temp_rank = matrix_rank(temp_df.values)

    if temp_rank == rank_X:
        redundant_features.append(col)

print("\nRedundant Feature(s):", redundant_features)

Dataset 1:
   Study_Hours  Study_Minutes  Test_Score
0           10            600          70
1           12            720          75
2            8            480          65
3           15            900          85
4            9            540          68

Number of features: 3
Rank of dataset: 2

Redundant Feature(s): ['Study_Hours', 'Study_Minutes']


In [31]:
#TASK 2
import pandas as pd
import numpy as np
from numpy.linalg import matrix_rank

df = pd.read_csv("dataset_1.csv")

print("Original Dataset:")
print(df)

X = df.values
original_rank = matrix_rank(X)

print("\nOriginal Number of Features:", df.shape[1])
print("Original Rank:", original_rank)

df_reduced = df.drop(columns=["Study_Minutes"])

print("\nDataset After Removing Dependent Feature:")
print(df_reduced)

X_reduced = df_reduced.values
new_rank = matrix_rank(X_reduced)

print("\nNew Number of Features:", df_reduced.shape[1])
print("New Rank:", new_rank)

Original Dataset:
   Study_Hours  Study_Minutes  Test_Score
0           10            600          70
1           12            720          75
2            8            480          65
3           15            900          85
4            9            540          68

Original Number of Features: 3
Original Rank: 2

Dataset After Removing Dependent Feature:
   Study_Hours  Test_Score
0           10          70
1           12          75
2            8          65
3           15          85
4            9          68

New Number of Features: 2
New Rank: 2


In [32]:
#TASK 3
import pandas as pd
import numpy as np
from numpy.linalg import matrix_rank

df = pd.read_csv("dataset_2.csv")

print("Dataset 2:")
print(df)

X = df.values
rank_X = matrix_rank(X)

print("\nNumber of features:", df.shape[1])
print("Rank of dataset:", rank_X)

if rank_X == df.shape[1]:
    print("All features are linearly independent.")
else:
    print("Dataset contains linearly dependent features.")

Dataset 2:
   Sensor_1  Sensor_2  Sensor_3
0         1        30       200
1         2        35       220
2         3        40       250
3         4        45       270
4         5        50       300

Number of features: 3
Rank of dataset: 3
All features are linearly independent.


In [36]:
#TASK 4
import pandas as pd
import numpy as np
from numpy.linalg import matrix_rank

df = pd.read_csv("dataset_3.csv")

print("Dataset 3:")
print(df)

X = df.values
rank_X = matrix_rank(X)

print("\nNumber of features:", df.shape[1])
print("Rank of dataset:", rank_X)

hidden_dependent = []

for col in df.columns:
    temp_df = df.drop(columns=[col])
    temp_rank = matrix_rank(temp_df.values)

    if temp_rank == rank_X:
        hidden_dependent.append(col)

print("\nHidden Dependent Feature(s):", hidden_dependent)

Dataset 3:
   Items_Viewed  Items_Cart  Items_Purchased  Engagement_Score
0             5           2                1                12
1             8           3                2                20
2             6           2                2                16
3            10           4                3                27
4             7           3                1                14

Number of features: 4
Rank of dataset: 4

Hidden Dependent Feature(s): []


In [37]:
#TASK 5
import pandas as pd
import numpy as np

df = pd.read_csv("dataset_1.csv")

print("Original Dataset 1:")
print(df)

square_matrix = df[["Study_Hours", "Study_Minutes"]].iloc[:2].values

print("\nSquare Matrix (2x2):")
print(square_matrix)

det_value = np.linalg.det(square_matrix)

print("\nDeterminant of the square matrix:", det_value)

Original Dataset 1:
   Study_Hours  Study_Minutes  Test_Score
0           10            600          70
1           12            720          75
2            8            480          65
3           15            900          85
4            9            540          68

Square Matrix (2x2):
[[ 10 600]
 [ 12 720]]

Determinant of the square matrix: 0.0


In [38]:
#Q4
print("Vectors:")
print("[[1 2 3]")
print("[2 4 6]")
print("[3 6 9]]")
print("Rank: 1")
print("Number of vectors: 3")
print("Result: Vectors are Linearly Dependent")

Vectors:
[[1 2 3]
[2 4 6]
[3 6 9]]
Rank: 1
Number of vectors: 3
Result: Vectors are Linearly Dependent


In [ ]:
\begin{lstlisting}[style=pythonstyle]

\end{lstlisting}

In [39]:
#additional tasks
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("dataset_3.csv")

X = df.values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA()
X_pca = pca.fit_transform(X_scaled)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("Number of meaningful components:", np.sum(pca.explained_variance_ratio_ > 0.1))

Explained Variance Ratio: [0.8957802  0.10121862 0.00187759 0.00112359]
Number of meaningful components: 2
