In [2]:
from google.colab import files
uploaded = files.upload()

Saving exp4_gram_schmidt_dataset.csv to exp4_gram_schmidt_dataset.csv


In [3]:
#Q1
import numpy as np
import pandas as pd

A = pd.read_csv('exp4_gram_schmidt_dataset.csv')
X = A.values
W = np.dot(X.T, X)

print("\nDot Product Matrix:")
print(W)


Dot Product Matrix:
[[4069.   1535.5  1134.   1249.  ]
 [1535.5   771.25  502.    518.5 ]
 [1134.    502.    590.    372.  ]
 [1249.    518.5   372.    413.  ]]


In [4]:
#Q2
import pandas as pd
import numpy as np

data = pd.read_csv('exp4_gram_schmidt_dataset.csv')
X = data.values
cols = X.shape[1]

for i in range(cols):
    for j in range(i + 1, cols):
        dot = np.dot(X[:, i], X[:, j])
        if dot != 0:
            print("Dataset features are not orthogonal")
            print(f"Dot product of Feature {i+1} and Feature {j+1} = {dot}")
            exit()

print("Dataset features are orthogonal")

Dataset features are not orthogonal
Dot product of Feature 1 and Feature 2 = 1535.5
Dataset features are not orthogonal
Dot product of Feature 1 and Feature 3 = 1134.0
Dataset features are not orthogonal
Dot product of Feature 1 and Feature 4 = 1249.0
Dataset features are not orthogonal
Dot product of Feature 2 and Feature 3 = 502.0
Dataset features are not orthogonal
Dot product of Feature 2 and Feature 4 = 518.5
Dataset features are not orthogonal
Dot product of Feature 3 and Feature 4 = 372.0
Dataset features are orthogonal


In [1]:
#Q3
import pandas as pd

data = pd.read_csv('exp4_gram_schmidt_dataset.csv')
corr = data.corr()

print("Correlation matrix:\n")
print(corr)

print("\nHighly correlated feature pairs:\n")

cols = corr.columns

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if abs(corr.iloc[i, j]) > 0.7:
            print(f"{cols[i]} and {cols[j]} are highly correlated")

Correlation matrix:

           Feature_1  Feature_2  Feature_3  Feature_4
Feature_1   1.000000   0.295425   0.354698   0.576303
Feature_2   0.295425   1.000000   0.414182   0.643815
Feature_3   0.354698   0.414182   1.000000   0.452059
Feature_4   0.576303   0.643815   0.452059   1.000000

Highly correlated feature pairs:



In [2]:
#Q4
import pandas as pd
import numpy as np

data = pd.read_csv('exp4_gram_schmidt_dataset.csv')
X = data.values

noise = np.random.normal(0, 0.01, X.shape)
X_noisy = X + noise

print("\nNoisy data:")
print(X_noisy)


Noisy data:
[[ 1.59840443e+01  2.98381187e+00  9.61350084e-03  5.01997919e+00]
 [ 6.99374867e+00  5.29856847e-03 -2.21370625e-02 -2.49758367e-03]
 [ 1.29967508e+01  1.76381610e-03  1.99238387e+00  1.99419213e+00]
 [ 1.59945912e+01  1.99139939e+00 -1.56713762e-03  3.99155582e+00]
 [ 1.69767396e+01  5.98632418e+00  5.97296081e+00  4.99631816e+00]
 [ 1.29969260e+01  3.99448776e+00  3.00277700e+00  3.99523672e+00]
 [ 1.39775214e+01  2.00478795e+00  9.99847996e+00  5.00011911e+00]
 [ 1.50007044e+01  8.00185903e+00  1.30045266e+01  4.99689244e+00]
 [ 1.70049409e+01  4.00820168e+00  3.99897394e+00  4.99290055e+00]
 [ 1.15590728e-02  2.00610328e+00  1.41858337e-02  2.98943587e+00]
 [ 1.30098798e+01  7.99961778e+00  9.85297349e-01  5.00498146e+00]
 [ 1.40066196e+01  2.99690988e+00  1.22881034e-02  4.00835303e+00]
 [ 1.09950170e+01  6.99592404e+00  6.01459947e+00  5.00997929e+00]
 [ 1.59996694e+01  8.00431721e+00  1.08703178e-03  4.99721114e+00]
 [ 1.70142139e+01  7.99726789e+00  6.99856917e+00

In [1]:
#Q5
import numpy as np

def gram_schmidt(vectors):
    ortho = []

    for v in vectors:
        u = v.copy()

        for o in ortho:
            if np.dot(o, o) != 0:
                u = u - (np.dot(v, o) / np.dot(o, o)) * o

        if np.linalg.norm(u) != 0:
            ortho.append(u)

    return ortho


n = int(input("Enter number of vectors: "))
m = int(input("Enter dimension of vectors: "))

vectors = []

for i in range(n):
    print(f"Enter elements of vector {i+1}:")
    temp = list(map(float, input().split()))

    if len(temp) != m:
        print("Incorrect number of elements entered.")
        exit()

    vectors.append(np.array(temp))

orthogonal_vectors = gram_schmidt(vectors)

print("\nOrthogonal vectors:")
for v in orthogonal_vectors:
    print(v)

Enter number of vectors: 3
Enter dimension of vectors: 3
Enter elements of vector 1:
1 2 3
Enter elements of vector 2:
2 4 6
Enter elements of vector 3:
1 0 1

Orthogonal vectors:
[1. 2. 3.]
[ 0.71428571 -0.57142857  0.14285714]
